#include <stdio.h>
#include <stdlib.h>
#include <omp.h>

int main()
{
    int n;

    printf("Enter array size: ");
    scanf("%d", &n);

    int A[n];
    int square[n];

    #pragma omp parallel
    {
        // Only one thread generates array
        #pragma omp single
        {
            printf("Array generated by Thread-%d\n",
                   omp_get_thread_num());

            for(int i = 0; i < n; i++)
            {
                A[i] = rand() % 10;
            }
        }


        // Work divided among threads
        #pragma omp for
        for(int i = 0; i < n; i++)
        {
            square[i] = A[i] * A[i];

            printf("Element %d processed by Thread-%d\n",
                   i, omp_get_thread_num());
        }
    }


    printf("\nOriginal\tSquare\n");

    for(int i = 0; i < n; i++)
    {
        printf("%d\t\t%d\n", A[i], square[i]);
    }

    return 0;
}